Projekt_TO/Projekt_TO/urls.py
from django.contrib import admin
from django.urls import path, include

from Projekt_TO.views import home_view

urlpatterns = [
   path('', home_view),
   path('admin/', admin.site.urls),
   path('tablica_ogloszen/', include('tablica_ogloszen.urls', namespace='tablica_ogloszen')),
]

Projekt_TO/tablica_ogloszen/urls.py
from django.urls import path
from . import views

app_name = 'tablica_ogloszen'

urlpatterns = [
   path('', views.question_list, name='question_list'),
   path('<int:question_id>/', views.question_detail, name='question_detail'),
   path('<int:question_id>/', views.announcement_list, name='announcement_list'),
]

Projekt_TO/tablica_ogloszen/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class Categories(models.Model):
    class Meta:
       verbose_name = 'Categories'
       verbose_name_plural = 'Categories'

    name = models.CharField(max_length=200)


    def __str__(self):
        return self.name

class Announcement(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    description = models.CharField(max_length=200)
    categories = models.ForeignKey(Categories, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.name

class Comments(models.Model):

    class Meta:
       verbose_name = 'Comment'
       verbose_name_plural = 'Comments'

    name = models.CharField(max_length=200)
    likes = models.IntegerField(default=0)
    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    phoneNumber = models.CharField(max_length=9)

Projekt_TO/Projekt_TO/views.py
from django.shortcuts import render

def home_view(request):
   print(request.user)
   return render(request, 'home.html')

Projekt_TO/tablica_ogloszen/views.py
from django.shortcuts import render, get_object_or_404
from .models import Announcement, AbstractUser


def question_list(request):
   announcements = Announcement.objects.all()
   return render(request, 'tablica_ogloszen/question_list.html', {'announcements': announcements})

def question_detail(request, question_id):
   question = get_object_or_404(Announcement, pk=question_id)
   return render(request, 'tablica_ogloszen/question_detail.html', {'announcement': question})

def announcement_list(request):
   abstractUser = AbstractUser.objects.all()
   return render(request, 'tablica_ogloszen/announcement_list.html', {'abstractUser': abstractUser})

Projekt_TO/tablica_ogloszen/templates/home.html
{% load static %}
<link rel="stylesheet" href="{% static 'tablica_ogloszen/lol.css' %}">
<h1>Witaj serdecznie na naszej tablicy ogłoszeń!</h1>

{% if user.is_authenticated %}
    <p>Cześć, {{ user }}</p>
{% else %}
    <p>Nie jesteś zalogowany</p>
{% endif %}

<a href="{% url 'tablica_ogloszen:question_list'%}" style="text-decoration:none;" >
    <button type="button" class="block" >
        Ogłoszenia
    </button>
</a>

<a href="{% url 'admin:index' %}" style="text-decoration:none;" >
   <button type="button" class="block2">
       Admin panel
   </button>
</a>

Projekt_TO/tablica_ogloszen/templates/tablica_ogloszen/announcement_list.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div>
    <table>
        <tr>
            <th>użytkownicy</th>
        </tr>
   {% for AbstractUser in CustomUser %}
       <tr>
                <td>{{ AbstractUser.id }}</td>
                <td>{{ abstractUser.first_name }}</td>
                <td>{{abstractUser.last_name}}</td>
                <td>{{ abstractUser.username }}</td>
                <td>{{ abstractUser.phone_Number }}</td>
                <td>{{ abstractUser.email }}</td>
                <td>{{ abstractUser.is_staff }}</td>
                <td>{{ abstractUser.is_active }}</td>
                <td>{{ abstractUser.is_superuser }}</td>

       </tr>
   {% endfor %}
    </table>
</div>
</body>
</html>

Projekt_TO/tablica_ogloszen/templates/tablica_ogloszen/question_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'tablica_ogloszen/lol.css' %}">
<h1>Kategoria: {{ announcement.categories }}</h1>
<h1>Tytuł: {{ announcement.name }}</h1>
<h1>Cena: {{ announcement.price }}zł</h1>
<h1>Opis: {{ announcement.description }}</h1>


<ul>
    <h2>Komentarze: </h2>
{% for comments in announcement.comments_set.all %}
    <ul>
       <li>{{ comments.name    }} ---------Polubienia:   {{ comments.likes }}</li>
    </ul>
{% endfor %}
</ul>

Projekt_TO/tablica_ogloszen/templates/tablica_ogloszen/question_list.html
{% load static %}
<link rel="stylesheet" href="{% static 'tablica_ogloszen/lol.css' %}">
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div>
    <h1>TABLICA OGŁOSZEŃ</h1>
    <table>
        <tr class="solid">
            <th>Kategoria ogłoszenia</th>
            <th>Treść</th>
            <th>Opis</th>
            <th>Cena</th>
        </tr>
   {% for announcement in announcements %}
       <tr>
                <td class="cat">{{ announcement.categories }}</td>
                <td class="name"><button class="but3"><a href="{% url 'tablica_ogloszen:question_detail' announcement.id %}" style="text-decoration:none;">
                {{ announcement.name }}</a></button>
                </td>
                <td class="description">{{ announcement.description }}</td>
                <td class="price">{{announcement.price}}zł</td>
       </tr>
   {% endfor %}
    </table>
    <h3>Użytkownicy</h3>
</div>
</body>
</html>